AWSTemplateFormatVersion: "2010-09-09"
Description: "Itport AWS VPC Networks"
Resources:
   
  # VPC Create
  ItportVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      InstanceTenancy: default
      Tags:
      - Key: "Name"
        Value: "ItportVPC"
 
  # IGW Create
  ItportIGW:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
      - Key: "Name"
        Value: "ItportIGW"
 
  # Attach IGW to VPC
  ItportIGWAttachVPC:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref ItportIGW
      VpcId: !Ref ItportVPC
 
  # Subnet(1a) Create
  ItportSubnet1a:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ItportVPC
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
      - Key: "Name"
        Value: "ItportSubnet1a"
 
  # RouteTable Create
  ItportRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref ItportVPC
      Tags:
      - Key: "Name"
        Value: "ItportRouteTable"
 
  # Internet Route Create
  ItportInternetRoute:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref ItportIGW
      RouteTableId: !Ref ItportRouteTable
   
  # Associate Route Table To Subnet
  AssociateItportSubnet1aToItportRouteTable:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref ItportRouteTable
      SubnetId: !Ref ItportSubnet1a
 
Outputs:
  ItportVPC:
    Value: !Ref ItportVPC
    Export:
      Name: ItportVPC
   
  ITPortSubnet1a:
    Value: !Ref ItportSubnet1a
    Export:
      Name: ItportSubnet1a